Milestone4
MkrtichSargsyan/microverse-calculator pull request #3
Opened 2021-07-21 19:27 UTC by MkrtichSargsyan

In this milestone I:

1-Created a new logic folder 
2-added big.js to handle bignums
3 -created operate function

2021-07-21 20:00 UTC, afanimartin requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work on this milestone. You have had quite progress. Well done!

### Changes 🔕 🔕 🔕 
- check my comments for suggestions


### Martin Afani 
#### Slack: whiz25

2021-07-21 20:00 UTC, afanimartin commented on .history/README_20210707035331.md
> +3d calculator
- write a more professional description. tell others what the project is all about

2021-07-21 20:00 UTC, afanimartin commented on .history/README_20210707035331.md
> +## Author
- add section for getting started. give commands for installing packages, cloning, and running the project locally

2021-07-21 20:00 UTC, afanimartin commented on src/components/App.jsx
> +// import calculate from '../logic/calculate';
- remove this comment. it makes your code look ugly
- you should import the `calculate.js` module here

2021-07-21 20:00 UTC, afanimartin commented on src/logic/calculate.js
> +// import operate from './operate';
- remove all comments from the codebase
- add operations for `.` and `=` buttons

2021-07-21 20:00 UTC, afanimartin commented on src/logic/operate.js
> +      result = x.times(y) / 100;
- change this to: `result = x.mod(y)`

2021-07-21 20:16 UTC, MkrtichSargsyan commented on .history/README_20210707035331.md
> +3d calculator
Is there any specific reason to look at my history folder instead of looking at the description I currently have?

2021-07-21 20:20 UTC, MkrtichSargsyan commented on src/logic/calculate.js
> +// import operate from './operate';
I can't remove the commented imports because I get linter errors, But I will and ```.``` and ```=``` operations

2021-07-21 20:24 UTC, MkrtichSargsyan commented on .history/README_20210707035331.md
> +## Author
You are supposed to check the readme.md file

2021-07-21 22:12 UTC, taiwo2 requested changes
# STATUS: CHANGES REQUIRED ♻️ 
@MkrtichSargsyan well done on this milestone, for trying to implement suggested changes from the previous Code Reviewer:
### Highlights

- [ ] add operations for . and = buttons
- [ ] change this to: result = x.mod(y)
- [ ] Big package is added to package.json

#### To improve

- [ ] add a section for getting started. give commands for installing packages, cloning, and running the project locally
- [ ] you should import the `calculate.js` module here in your App.jsx 
- [ ] remove all comments from the codebase

### once specific changes are made kindly request for another review

2021-07-22 14:47 UTC, uche-inyama approved these changes
## Approved :heavy_check_mark: 

### Hi Mike :slightly_smiling_face: 

Move on to the next milestone.

### Happy coding :man_technologist: 

#### ``` Uchechukwu Henry Inyama ```

2021-07-28 08:34 UTC, merged